[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tourbillon-app"
version = "6.0.0"
description = "TourBillon - by La Billionnière"
authors = ["La Billonnière"]
license = "GNU GPL"
readme = ["README.md", "CHANGELOG.md"]
homepage = "https://github.com/anxuae/TourBillon"
repository = "https://github.com/anxuae/TourBillon"
keywords = ["billon", "game", "France", "Nord"]
packages = [
    { include = "tourbillon" }
]
include = [
    { path = "tourbillon/static/dist/**/*", format = ["sdist", "wheel"] },
    { path = "tests", format = "sdist"},
    { path = "LICENSE", format = "sdist"}
]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
numpy = "^2.0"
fastapi = "^0.111.0"
pydantic = "^2.7"
uvicorn = { extras = ["standard"], version = "^0.30.0" }

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^8.0"
pytest-asyncio = "^0.24"
pytest-cov = "^5.0"

[tool.poetry.group.build]
optional = true

[tool.poetry.group.build.dependencies]
pyinstaller = "^6.10"

[tool.poetry.scripts]
tourbillon = 'tourbillon.__main__:run'

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]

[tool.coverage.run]
source = ["tourbillon"]
branch = true

[tool.coverage.report]
omit = ["tourbillon/api/routers/__init__.py"]

